### PR TITLE
fix(extensions/nanoarrow_ipc): Fix crash and mixleading error messages resulting from corrupted streams

### LINKED ISSUE #287: Investigate crash when processing mangled streams
While testing nanoarrow's behavior with respect to error codes, a crasher was found. It can be reproduced with a short Python script that does the mangling and then runs the mangled stream through the dump_stream IPC helper.

Steps to reproduce:

1. Put https://gist.github.com/amoeba/b64fc94ba5224bafcb3734bd261181d5 in your working directory
2. Build nanoarrow_ipc with `NANOARROW_IPC_BUILD_APPS=ON` to get `dump_stream` and put it in your working directory
3. Run the attached script repeatedly until you get something like
    > dump_stream(53000,0x1f671a080) malloc: *** error for object 0x6000027b8050: pointer being freed was not allocated
    > dump_stream(53000,0x1f671a080) malloc: *** set a breakpoint in malloc_error_break to debug

In my early testing, it doesn't appear to be deterministic so you may have to run `test.py` repeatedly.

<details>
<summary><code>test.py</code></summary>

```python
import os
import base64
import subprocess

with open(os.path.join(os.path.dirname(__file__), "test_arrow_data")) as f:
    b64data = f.read()

decode_bytes = base64.b64decode(b64data)

for i in range(8):
    try:
        print(subprocess.check_output(["./dump_stream", "-"], input=decode_bytes[:i] + decode_bytes[i + 1 :]))
    except Exception as e:
        print(e)

```
</details>

<details>
<summary>Example output of running <code>test.py</code></summary>

```
❯ python test.py
stream.get_schema() returned 22 with error 'Expected 0xFFFFFFFF at start of message but found 0xE0FFFFFF'
Command '['./dump_stream', '-']' returned non-zero exit status 1.
stream.get_schema() returned 22 with error 'Expected 0xFFFFFFFF at start of message but found 0xE0FFFFFF'
dump_stream(53000,0x1f671a080) malloc: *** error for object 0x6000027b8050: pointer being freed was not allocated
dump_stream(53000,0x1f671a080) malloc: *** set a breakpoint in malloc_error_break to debug
Command '['./dump_stream', '-']' died with <Signals.SIGABRT: 6>.
stream.get_schema() returned 22 with error 'Expected 0xFFFFFFFF at start of message but found 0xE0FFFFFF'
Command '['./dump_stream', '-']' returned non-zero exit status 1.
stream.get_schema() returned 22 with error 'Expected 0xFFFFFFFF at start of message but found 0xE0FFFFFF'
Command '['./dump_stream', '-']' returned non-zero exit status 1.
stream.get_schema() returned 29 with error 'Expected 0 <= message body size <= 32943 bytes but found message body size of 268435500 bytes'
Command '['./dump_stream', '-']' returned non-zero exit status 1.
stream.get_schema() returned 29 with error 'Expected 0 <= message body size <= 32943 bytes but found message body size of 268435680 bytes'
Command '['./dump_stream', '-']' returned non-zero exit status 1.
stream.get_schema() returned 29 with error 'Expected 0 <= message body size <= 32943 bytes but found message body size of 268446944 bytes'
Command '['./dump_stream', '-']' returned non-zero exit status 1.
stream.get_schema() returned 29 with error 'Expected 0 <= message body size <= 32943 bytes but found message body size of 268446944 bytes'
Command '['./dump_stream', '-']' returned non-zero exit status 1.
```
</details>

### PR DESCRIPTION
**Pull request by paleolimbot**
Closes #287.

The reported crash occurred because the internal `ArrowIpcDecoderVerifyHeader()` incorrectly interpreted the return value of `ArrowIpcDecoderCheckHeader()`. Because the header checker returned an error code sometimes even if it succeeded, we had been ignoring the error in `ArrowIpcDecoderVerifyHeader()` which resulted in issuing commands like `memcpy(dst, src, -8)`. I believe that's undefined behaviour, leading to the intermittent nature of the crash.

In adding tests for this kind of error, I also made some improvements to error messages along the way.

```bash
# docker run --rm -it ghcr.io/apache/arrow-nanoarrow:ubuntu
# git clone https://github.com/apache/arrow-nanoarrow.git /arrow-nanoarrow
# or
# docker run --rm -it -v$(pwd):/arrow-nanoarrow ghcr.io/apache/arrow-nanoarrow:ubuntu

cd /arrow-nanoarrow/extensions/nanoarrow_ipc
mkdir build && cd build
cmake .. -DNANOARROW_IPC_BUILD_APPS=ON

curl https://gist.githubusercontent.com/amoeba/b64fc94ba5224bafcb3734bd261181d5/raw/af4c93da7ce6affba74a80e1ba94ed9573e91be8/test_arrow_data | \
    base64 -d > test_binary

with_byte_removed() {
    BYTE_PLUS_ONE=$(($2 + 2))
    cat $1 | head -c $2
    cat $1 | tail -c "+$BYTE_PLUS_ONE"
}

cmake --build .

echo "Errors:" > out.txt
for i in {1..32951}; do
  echo "$i/32951"
  echo "$i/32951" >> out.txt
  with_byte_removed test_binary $i | ./dump_stream - 2>> out.txt
done
```

### CODE REVIEW

File: extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder.c [hunk 1]
```diff
@@ -930,7 +930,8 @@ static inline void ArrowIpcDecoderResetHeaderInfo(struct ArrowIpcDecoder* decode
 }
 
 // Returns NANOARROW_OK if data is large enough to read the message header,
```
Comment (lidavidm) [inline extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder.c:932]: I guess this docstring is slightly misleading then because it may return 0 even if the buffer technically does not contain the entire header; it just has to contain the continuation token and size?

File: extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder.c [hunk 2]
```diff
@@ -1025,6 +1029,16 @@ ArrowErrorCode ArrowIpcDecoderDecodeHeader(struct ArrowIpcDecoder* decoder,
   NANOARROW_RETURN_NOT_OK(
       ArrowIpcDecoderCheckHeader(decoder, &data, &decoder->header_size_bytes, error));
 
+  // Check that data contains at least the entire header (return ESPIPE to signal
+  // that reading more data may help).
+  int64_t message_body_size = decoder->header_size_bytes - 8;
```
Comment (lidavidm) [inline extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder.c:1034]: nit: above we use `2 * sizeof(int32_t)` but here we hardcode 8; maybe just pull it out into a constant?

File: extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_reader_test.cc [hunk 3]
```diff
@@ -291,6 +291,62 @@ TEST(NanoarrowIpcReader, StreamReaderExpectedSchema) {
...
+    memcpy(simple_stream_invalid + i, kSimpleSchema + (i + 1),
+           (sizeof(kSimpleSchema) - i));
+
+    ArrowBufferInit(&input_buffer);
+    ASSERT_EQ(ArrowBufferAppendBufferView(&input_buffer, data), NANOARROW_OK);
+    ASSERT_EQ(ArrowIpcInputStreamInitBuffer(&input, &input_buffer), NANOARROW_OK);
+    ASSERT_EQ(ArrowIpcArrayStreamReaderInit(&stream, &input, nullptr), NANOARROW_OK);
+
+    ASSERT_NE(stream.get_schema(&stream, &schema), NANOARROW_OK)
+        << "After removing Schema message byte " << i;
```
Comment (lidavidm) [inline extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_reader_test.cc:320]: FWIW, you can `SCOPED_TRACE` inside the loop and have it apply to all the assertions (though building up the message is a little annoying)

**Review by lidavidm — APPROVED** [review]

File: extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_reader_test.cc (hunk 3 above)
Comment (paleolimbot) [reply extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_reader_test.cc:320]: Nice!

```
/Users/deweydunnington/Desktop/rscratch/arrow-nanoarrow/extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_reader_test.cc:345: Failure
Expected: (stream.get_next(&stream, &array)) != (0), actual: 0 vs 0
Google Test trace:
/Users/deweydunnington/Desktop/rscratch/arrow-nanoarrow/extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_reader_test.cc:332: 144
```

File: extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder.c (hunk 1 above)
Comment (paleolimbot) [reply extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder.c]: Good catch! I also renamed the function since it's more reading than checking now.

**Review by lidavidm — APPROVED** [review]
