### PR TITLE
fix(ci): Use cached Arrow C++ build in CI

### LINKED ISSUE #408: ci: Download from jfrog in CI is broken
CI is having trouble downloading the Arrow C++ linux package:

https://github.com/apache/arrow-nanoarrow/actions/runs/8391757314/job/22982828414?pr=405#step:3:198

```
 Resolving landing.jfrog.com (landing.jfrog.com)... 18.232.172.199, 18.214.194.113, 3.95.117.170
Connecting to landing.jfrog.com (landing.jfrog.com)|18.232.172.199|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11533 (11K) [text/html]
Saving to: ‘apache-arrow-apt-source-latest-jammy.deb’

     0K .......... .                                          100% 1.81M=0.006s

2024-03-22 14:20:58 (1.81 MB/s) - ‘apache-arrow-apt-source-latest-jammy.deb’ saved [11533/11533]

Reading package lists...
E: Invalid archive signature
E: Internal error, could not locate member control.tar{.zst,.lz4,.gz,.xz,.bz2,.lzma,}
E: Could not read meta data from /home/runner/work/arrow-nanoarrow/arrow-nanoarrow/apache-arrow-apt-source-latest-jammy.deb
E: The package lists or status file could not be parsed or opened.
```

From visiting the HTML version, it seems like a "free trial" expired:

Screenshot 2024-03-22 at 11 39 13 AM

### PR DESCRIPTION
**Pull request by paleolimbot**
This PR removes the use of the debian packages for Arrow C++ in favour of a minimal (cached) build. This is slightly faster than installing and removes the dependence on the artifactory for CI to pass (which is temporarily not available).

It also updates some of the actions, which were using old checkout/cache versions or installing Arrow C++ unnecessarily.

Closes #408.

### CODE REVIEW

File: ci/scripts/build-arrow-cpp-minimal.sh [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+fi
+
+ARROW_CPP_INSTALL_DIR="$(cd "${ARROW_CPP_INSTALL_DIR}" && pwd)"
+
+ARROW_CPP_SCRATCH_DIR="arrow-cpp-build-${ARROW_CPP_VERSION}"
+
+mkdir "${ARROW_CPP_SCRATCH_DIR}"
+pushd "${ARROW_CPP_SCRATCH_DIR}"
+
+curl https://dlcdn.apache.org/arrow/arrow-${ARROW_CPP_VERSION}/apache-arrow-${ARROW_CPP_VERSION}.tar.gz | \
```
Comment (assignUser) [inline ci/scripts/build-arrow-cpp-minimal.sh:53]: The canonical url uses `closer.lua` e.g. `https://www.apache.org/dyn/closer.lua?action=download&filename=arrow/arrow-15.0.2/apache-arrow-15.0.2.tar.gz`

Ideally you should also check the sha but as this is only used for testing it's not critical.

File: .github/workflows/build-and-test-ipc.yaml [hunk 2]
```diff
@@ -51,36 +51,46 @@ jobs:
       NANOARROW_ARROW_TESTING_DIR: '${{ github.workspace }}/arrow-testing'
 
     steps:
-      - name: Checkout repo
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
```
Comment (assignUser) [inline .github/workflows/build-and-test-ipc.yaml:57]: Yeah I don't see you doing anything that would require a full checkout (e.g. changing branch/using tags etc.) :+1:

File: .github/workflows/build-and-test-device.yaml [hunk 3]
```diff
@@ -50,27 +50,12 @@ jobs:
...
+      - name: Install memcheck dependencies
+        if: matrix.config.label == 'default-build'
         run: |
-          sudo apt-get update
-          sudo apt install -y -V ca-certificates lsb-release wget cmake valgrind
-          wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
-          sudo apt-get install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
-          sudo apt-get update
-          sudo apt-get install -y -V libarrow-dev
-          rm apache-arrow-apt-*.deb
```
Comment (assignUser) [inline .github/workflows/build-and-test-device.yaml:73]: You are removing the installation of arrow here but I don't see the cache/build being added? Was it not needed?

**Review by assignUser — APPROVED** [review]
Looks good, a few comments

File: .github/workflows/build-and-test-device.yaml (hunk 3 above)
Comment (paleolimbot) [reply .github/workflows/build-and-test-device.yaml:73]: Apparently not! I think it was just copied by accident.
