### PR TITLE
[C] Fix AppendDouble to accept all values on float arrays

### LINKED ISSUE #75: [C] AppendDouble doesn't work with most floats
AppendDouble checks that the value is in the range `[FLT_MIN, FLT_MAX]` before appending. However, that's not actually the right check: `FLT_MIN` isn't the "minimum float value" (that doesn't make sense; floats contain infinity), but rather the smallest positive float. Hence, 0 and any negative float will get wrongly rejected.

IMO, it might make sense to just accept any double and cast it to float without thinking. Otherwise, maybe the right check is `(double)((float) v) == v` or something ("is this double exactly representable as a float", perhaps there's an idiom for this though I can't get the right search query to figure this out), though this will not work for NaN.

### PR DESCRIPTION
**Pull request by lidavidm**
Fixes #75.

### CODE REVIEW

File: src/nanoarrow/array_inline.h [hunk 1]
```diff
@@ -303,10 +303,10 @@ static inline ArrowErrorCode ArrowArrayAppendDouble(struct ArrowArray* array,
     case NANOARROW_TYPE_DOUBLE:
       NANOARROW_RETURN_NOT_OK(ArrowBufferAppend(data_buffer, &value, sizeof(double)));
       break;
-    case NANOARROW_TYPE_FLOAT:
-      _NANOARROW_CHECK_RANGE(value, FLT_MIN, FLT_MAX);
-      NANOARROW_RETURN_NOT_OK(ArrowBufferAppendFloat(data_buffer, value));
+    case NANOARROW_TYPE_FLOAT: {
+      NANOARROW_RETURN_NOT_OK(ArrowBufferAppendFloat(data_buffer, (float)value));
       break;
+    }
```
Comment (paleolimbot) [inline src/nanoarrow/array_inline.h:309]:
```suggestion
    case NANOARROW_TYPE_FLOAT:
      NANOARROW_RETURN_NOT_OK(ArrowBufferAppendFloat(data_buffer, (float)value));
      break;
```

(Feel free to revert, just a bit out of place with the other cases here)

**Review by paleolimbot — APPROVED** [review]
Thank you! Feel free to take or leave the switch case thing.

File: src/nanoarrow/array_inline.h (hunk 1 above)
Comment (lidavidm) [reply src/nanoarrow/array_inline.h:309]: Oh my bad, I added it because I added a declaration then changed my mind.
