### PR TITLE
fix(r): sub-day precision Date should be floored when treated as integer

### LINKED ISSUE #665: [R] Sub-day precision Date class must be converted to integers by floor, not trunc
I noticed that the conversion of Date type with sub-day precision is not correct.
`arrow` package has the same problem (apache/arrow#44502).

``` r
d <- as.Date(-0.1)
d
#> [1] "1969-12-31"
as.vector(nanoarrow::as_nanoarrow_array(d))
#> [1] "1970-01-01"
```

<sup>Created on 2024-10-22 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by eitsupi**
Fix #665

### CODE REVIEW

File: r/tests/testthat/test-as-array.R [hunk 1]
```diff
@@ -464,7 +464,13 @@ test_that("as_nanoarrow_array() works for Date -> na_date32()", {
   expect_identical(as.raw(array$buffers[[1]]), as.raw(0x03))
   expect_identical(
     as.raw(array$buffers[[2]]),
-    as.raw(as_nanoarrow_buffer(c(10957L, 19391L, NA)))
+    as.raw(as_nanoarrow_buffer(c(10957L, 19391L, 0L)))
```
Comment (eitsupi) [inline r/tests/testthat/test-as-array.R:467]: I do not know why this change occurred.
(I also do not understand what this test means.)

**Review by eitsupi — COMMENTED** [review]
As a side note, it seems that date32 is currently output as a double vector in R, but I think integer is fine. (And that would be more efficient, right?)

File: r/R/as-array.R [hunk 2]
```diff
@@ -262,8 +262,14 @@ as_nanoarrow_array.Date <- function(x, ..., schema = NULL) {
   switch(
     parsed$type,
     date32 = {
+      int_vec <- if (is.integer(x)) {
+        as.integer(x)
```
Comment (paleolimbot) [inline r/R/as-array.R:266]:
```suggestion
        x
```

**Review by paleolimbot — APPROVED** [review]
Thank you! Just one nit.

> As a side note, it seems that date32 is currently output as a double vector in R, but I think integer is fine. (And that would be more efficient, right?)

This is to better align with how base R normally handles this (although I think either are OK).

``` r
typeof(as.Date("2001-02-03"))
#> [1] "double"
typeof(Sys.Date())
#> [1] "double"
```

File: r/R/as-array.R (hunk 2 above)
Comment (eitsupi) [reply r/R/as-array.R]: Thinking about it again, I think this is necessary to remove the class attribute (without it, wouldn't we be stuck in an endless loop?).

Comment (paleolimbot) [reply r/R/as-array.R:266]: Ah, I didn't get that from reading. Either a comment or an `unclass(x)` would work for me so that we don't accidentally simplify this later!

**Comment by eitsupi** [comment]
> This is to better align with how base R normally handles this (although I think either are OK).
> 
> ```r
> typeof(as.Date("2001-02-03"))
> #> [1] "double"
> typeof(Sys.Date())
> #> [1] "double"
> ```

Indeed, it seems that when a number is converted to Date with `as.Date()`, the original numeric type is preserved.
So I think it does not seem surprising that the output of nanoarrow would be an integer.

``` r
typeof(as.Date(1L))
#> [1] "integer"
```

<sup>Created on 2024-11-03 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
